# Generated by Django 5.2.7 on 2025-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_facebookcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='meetup_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='save_as_draft',
            field=models.BooleanField(default=False),
        ),
    ]
