# Generated by Django 5.2.7 on 2025-10-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_meetup_preference_listing_save_as_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tabs',
            field=models.IntegerField(default=1),
        ),
    ]
